---
title: "Modeling (Support Vector Machine)"
author: Sebastian Deri
output:
  html_document:
    df_print: paged
    code_folding: show
---

[return to [overview page](./hld_OVERVIEW.html)]

I will now build a neural network predictive model.

# Packages

Again, I will start by loading relevant packages.

```{r, message=FALSE, warning=FALSE}
# before knitting: message = FALSE, warning = FALSE
library(tidyverse) # cleaning and visualization
library(ggthemes) # visualization
library(caret) # modeling
library(AppliedPredictiveModeling)
library(pROC) # ROC curve
```


# Load Data

Next, I will load the various cleaned versions of the data we just
created.

```{r}
# load all the nice tidy df's of features we created (remember stats_words has multiple dtm's)
load("stats_all.Rda")

```

## Step 1a: Split the Data (Index)

```{r}
# get index for random 50% of data, and count this as training data (rest will be test)
index_neural <- createDataPartition(y = stats_all$grd_truth,
                                 p = 0.50,
                                 list = FALSE)

# check length (should be 2502)
length(index_neural)
```

## Step 1b: Split the Data (Actual Train and Test Set)

```{r}
train_neural <- stats_all[index_neural, ]
test_neural <- stats_all[-index_neural, ]
```


```{r}
# train model

nnetGrid <- expand.grid(.size = 1:10,
                        .decay = c(0, .1, 1, 2))
maxSize <- max(nnetGrid$.size)
numWts <- (maxSize * (length(names(stats_all))) + maxSize + 1)

model_neural <-
  train(x = train_neural[, !(names(train_neural) %in% c("stat_id", "grd_truth"))],
        y = train_neural$grd_truth,
        method = "nnet",
        preProc = c("center", "scale", "spatialSign"),
        # maxit = 2000,
        trace = FALSE,
        # MaxNWts = numWts,
        tuneGrid = nnetGrid)

# get predictions of model
neural_predicts <-
  predict(object = model_neural,
          newdata = test_neural[, !(names(train_neural) %in% c("stat_id", "grd_truth"))])

# confusion matrix, with results
confusionMatrix(neural_predicts, test_neural$grd_truth)
```



```{r}
# # -----------------------------------------------------------------------------
# STEP 1: decide how many times to run the model
rounds <- 10

# -----------------------------------------------------------------------------
# STEP 2: set up object to store results
# part a: create names of results to store
result_cols <- c("model_type", "round", "accuracy", "accuracy_LL", "accuracy_UL",
                 "sensitivity", "specificity", "precision", "npv")

# part b: create matrix
results <-
  matrix(nrow = rounds,
         ncol = length(result_cols))

# part c: actually name columns in results marix
colnames(results) <- result_cols

# part d: convert to df (so multiple variables of different types can be stored)
results <- data.frame(results)

# -----------------------------------------------------------------------------
# STEP 2: start timer
start_time <- Sys.time()

# -----------------------------------------------------------------------------
# STEP 3: create rounds number of models, and store results each time

for (i in 1:rounds){
  
  # part a: partition data in 50-50 lgocv split (create index for test set)
  index_train <- 
    createDataPartition(y = stats_proc$stat_id,
                        p = 0.50,
                        times = 1,
                        list = FALSE)
  
  # part b: create testing and training data sets
  train_set <- stats_proc[index_train, ]
  test_set <- stats_proc[-index_train, ]
  
  
  # part c: use caret "train" function to train logistic regression model
  model <- 
    train(form = grd_truth ~ . - stat_id,
          data = train_set,
          method = "nnet",
          trace = FALSE)
  
  # part d: make predictions
  preds <-
    predict(object = model,
            newdata = test_set,
            type = "raw")
  
  # part e: store model performance
  conf_ex <-
    confusionMatrix(data = preds,
                    reference = test_set$grd_truth,
                    positive = "truth")
  
  # part f: store model results
  # model type
  results[i, 1] <- "logistic"
  # round
  results[i, 2] <- i
  # accuracy
  results[i, 3] <- conf_ex$overall[1]
  # accuracy LL
  results[i, 4] <- conf_ex$overall[3]
  # accuracy UL
  results[i, 5] <- conf_ex$overall[4]
  # sensitivity
  results[i, 6] <- conf_ex$byClass[1]
  # specificity
  results[i, 7] <- conf_ex$byClass[2]
  # precision
  results[i, 8] <- conf_ex$byClass[3]
  # negative predictive value
  results[i, 9] <- conf_ex$byClass[4]
  
  # part g: print round and total elapsed time so far
  cumul_time <- difftime(Sys.time(), start_time, units = "mins")
  print(paste("round #", i, ": cumulative time ", round(cumul_time, 2), " mins",
              sep = ""))
  print("--------------------------------------")

}

```

```{r}
results
```


